In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("https://raw.githubusercontent.com/kun9717/STIN-data-set/main/SAT20.csv")

In [20]:
df

,id,fl_dur,fw_pk,l_fw_pkt,l_bw_pkt,pkt_len_min,pkt_len_max,pkt_len_std,fl_byt_s,fl_iat_min,...,down_up_ratio,fw_byt_blk_avg,fw_pkt_blk_avg,fw_blk_rate_avg,bw_byt_blk_avg,bw_pkt_blk_avg,bw_blk_rate_avg,fw_win_byt,bw_win_byt,Label
0,1,1,2,0,0,0,0,0.000000,0.000000e+00,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
1,2,1,2,0,0,0,0,0.000000,0.000000e+00,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
2,3,0,2,0,0,0,0,0.000000,0.000000e+00,0,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
3,4,1,2,0,0,0,0,0.000000,0.000000e+00,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
4,5,1,2,0,0,0,0,0.000000,0.000000e+00,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82315,82316,213696,6,2088,0,321,393,35.088460,9.770889e+03,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82316,82317,108457,4,1438,0,330,389,34.063666,1.325871e+04,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82317,82318,1,2,766,0,383,383,0.000000,7.660000e+08,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82318,82319,107847,4,1438,0,330,389,34.063666,1.333370e+04,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82319,82320,1,2,750,0,375,375,0.000000,7.500000e+08,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS

In [21]:
df.head()

,id,fl_dur,fw_pk,l_fw_pkt,l_bw_pkt,pkt_len_min,pkt_len_max,pkt_len_std,fl_byt_s,fl_iat_min,...,down_up_ratio,fw_byt_blk_avg,fw_pkt_blk_avg,fw_blk_rate_avg,bw_byt_blk_avg,bw_pkt_blk_avg,bw_blk_rate_avg,fw_win_byt,bw_win_byt,Label
0,1,1,2,0,0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
1,2,1,2,0,0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
2,3,0,2,0,0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
3,4,1,2,0,0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS
4,5,1,2,0,0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,0,5840,-1,Syn_DDoS

In [22]:
df.tail()

,id,fl_dur,fw_pk,l_fw_pkt,l_bw_pkt,pkt_len_min,pkt_len_max,pkt_len_std,fl_byt_s,fl_iat_min,...,down_up_ratio,fw_byt_blk_avg,fw_pkt_blk_avg,fw_blk_rate_avg,bw_byt_blk_avg,bw_pkt_blk_avg,bw_blk_rate_avg,fw_win_byt,bw_win_byt,Label
82315,82316,213696,6,2088,0,321,393,35.088460,9.770889e+03,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82316,82317,108457,4,1438,0,330,389,34.063666,1.325871e+04,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82317,82318,1,2,766,0,383,383,0.000000,7.660000e+08,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82318,82319,107847,4,1438,0,330,389,34.063666,1.333370e+04,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS
82319,82320,1,2,750,0,375,375,0.000000,7.500000e+08,1,...,0,0,0,0,0,0,0,-1,-1,UDP_DDoS

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82320 entries, 0 to 82319
Data columns (total 32 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               82320 non-null  int64
 1   fl_dur           82320 non-null  int64
 2   fw_pk            82320 non-null  int64
 3   l_fw_pkt         82320 non-null  int64
 4   l_bw_pkt         82320 non-null  int64
 5   pkt_len_min      82320 non-null  int64
 6   pkt_len_max      82320 non-null  int64
 7   pkt_len_std      82320 non-null  float64
 8   fl_byt_s         82320 non-null  float64
 9   fl_iat_min       82320 non-null  int64
 10  bw_iat_tot       82320 non-null  int64
 11  bw_iat_min       82320 non-null  int64
 12  bw_psh_flag      82320 non-null  int64
 13  fw_urg_flag      82320 non-null  int64
 14  bw_urg_flag      82320 non-null  int64
 15  fw_hdr_len       82320 non-null  int64
 16  bw_pkt_s         82320 non-null  float64
 17  fin_cnt          82320 non-null  int64
 18  syn_cnt          82320 non-null  int64
 19  psh_cnt          82320 non-null  int64
 20  urg_cnt          82320 non-null  int64
 21  ece_cnt          82320 non-null  int64
 22  down_up_ratio    82320 non-null  int64
 23  fw_byt_blk_avg   82320 non-null  int64
 24  fw_pkt_blk_avg   82320 non-null  int64
 25  fw_blk_rate_avg  82320 non-null  int64
 26  bw_byt_blk_avg   82320 non-null  int64
 27  bw_pkt_blk_avg   82320 non-null  int64
 28  bw_blk_rate_avg  82320 non-null  int64
 29  fw_win_byt       82320 non-null  int64
 30  bw_win_byt       82320 non-null  int64
 31   Label           82320 non-null  object
dtypes: float64(3), int64(28), object(1)
memory usage: 20.1+ MB

In [24]:
df.describe()

,id,fl_dur,fw_pk,l_fw_pkt,l_bw_pkt,pkt_len_min,pkt_len_max,pkt_len_std,fl_byt_s,fl_iat_min,...,ece_cnt,down_up_ratio,fw_byt_blk_avg,fw_pkt_blk_avg,fw_blk_rate_avg,bw_byt_blk_avg,bw_pkt_blk_avg,bw_blk_rate_avg,fw_win_byt,bw_win_byt
count,82320.000000,8.232000e+04,82320.000000,82320.000000,82320.000000,82320.000000,82320.000000,82320.000000,8.232000e+04,82320.000000,...,82320.0,82320.000000,82320.0,82320.0,82320.0,82320.0,82320.0,82320.0,82320.00000,82320.000000
mean,41160.500000,3.947447e+06,3.378814,708.834961,0.130005,188.334402,203.488618,8.002540,1.669075e+08,4.769096,...,0.0,0.045396,0.0,0.0,0.0,0.0,0.0,0.0,2772.81510,-0.552077
std,23763.881417,1.913993e+07,3.148802,1010.742394,19.871152,181.233350,194.271215,13.763823,3.143924e+08,13.602784,...,0.0,0.208464,0.0,0.0,0.0,0.0,0.0,0.0,2934.47421,100.974508
min,1.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-1.00000,-1.000000
25%,20580.750000,1.000000e+00,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-1.00000,-1.000000
50%,41160.500000,1.000000e+00,2.000000,750.000000,0.000000,321.000000,369.000000,0.000000,9.294501e+03,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-1.00000,-1.000000
75%,61740.250000,1.067492e+05,4.000000,1398.000000,0.000000,375.000000,389.000000,22.516661,1.530612e+07,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,5840.00000,-1.000000
max,82320.000000,1.159349e+08,46.000000,22852.000000,4378.000000,1472.000000,1472.000000,314.655897,2.944000e+09,655.000000,...,0.0,3.000000,0.0,0.0,0.0,0.0,0.0,0.0,65535.00000,28960.000000

In [25]:
df.shape

(82320, 32)

In [26]:
df.columns

Index(['id', 'fl_dur', 'fw_pk', 'l_fw_pkt', 'l_bw_pkt', 'pkt_len_min',
       'pkt_len_max', 'pkt_len_std', 'fl_byt_s', 'fl_iat_min', 'bw_iat_tot',
       'bw_iat_min', 'bw_psh_flag', 'fw_urg_flag', 'bw_urg_flag', 'fw_hdr_len',
       'bw_pkt_s', 'fin_cnt', 'syn_cnt', 'psh_cnt', 'urg_cnt', 'ece_cnt',
       'down_up_ratio', 'fw_byt_blk_avg', 'fw_pkt_blk_avg', 'fw_blk_rate_avg',
       'bw_byt_blk_avg', 'bw_pkt_blk_avg', 'bw_blk_rate_avg', 'fw_win_byt',
       'bw_win_byt', ' Label'],
      dtype='object')

In [27]:
df[' Label']

0        Syn_DDoS
1        Syn_DDoS
2        Syn_DDoS
3        Syn_DDoS
4        Syn_DDoS
           ...
82315    UDP_DDoS
82316    UDP_DDoS
82317    UDP_DDoS
82318    UDP_DDoS
82319    UDP_DDoS
Name:  Label, Length: 82320, dtype: object

In [28]:
df[' Label'].value_counts()

 Label
UDP_DDoS    43244
Syn_DDoS    39076
Name: count, dtype: int64